server:
  port: 8080

spring:
  application:
    name: MailSense
  datasource:
    url: ${DUCKDB_URL}
    driver-class-name: ${DUCKDB_DRIVER}
    initialization-mode: ${DUCKDB_INIT_MODE}

# Flyway settings (runs automatically on startup)
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    table: flyway_schema_history