server:
  port: 8080

spring:
  application:
    name: mailsense
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mailsensedb}
    username: ${DB_USER:mailsense}
    password: ${DB_PASSWORD:mailsense}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000  # 10 min
      max-lifetime: 1800000  # 30 min
      connection-timeout: 30000 # 30 sec

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - openid
              - email
              - profile
              - https://www.googleapis.com/auth/gmail.readonly
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URIS:}
            client-name: Google
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 900000 # 15 minutes
  refresh-expiration-ms: 2592000000 # 30 days

oauth:
  base-url: ${APP_BASE_URL:http://localhost:8080}
  providers:
    google:
      auth-uri: https://accounts.google.com/o/oauth2/v2/auth
      token-uri: https://oauth2.googleapis.com/token
      userinfo-uri: https://openidconnect.googleapis.com/v1/userinfo

encryption:
  key: ${ENCRYPTION_KEY} # must be 32 bytes for AES-256-GCM; store safely

flyway:
  enabled: true
  baseline-on-migrate: true
  locations: classpath:db/migration
  url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mailsensedb}
  username: ${DB_USER:mailsense}
  password: ${DB_PASSWORD:mailsense}

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN