server:
  port: 8080

spring:
  application:
    name: mailsense
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:}
            client-secret: ${GOOGLE_CLIENT_SECRET:}
            scope:
              - openid
              - email
              - profile
              - https://www.googleapis.com/auth/gmail.readonly
            authorization-grant-type: authorization_code
            redirect-uri: ${REDIRECT_URIS:}
            client-name: Google
jwt:
  secret: ${JWT_SECRET}
  expiration-ms: 900000 # 15 minutes
  refresh-expiration-ms: 2592000000 # 30 days

oauth:
  base-url: ${APP_BASE_URL:http://localhost:8080}
  providers:
    google:
      auth-uri: https://accounts.google.com/o/oauth2/v2/auth
      token-uri: https://oauth2.googleapis.com/token
      userinfo-uri: https://openidconnect.googleapis.com/v1/userinfo

encryption:
  key: ${ENCRYPTION_KEY} # must be 32 bytes for AES-256-GCM; store safely

# replace any existing liquibase.change-log value
liquibase:
  enabled: true
  change-log: classpath:db/changelog/db.changelog-master.yaml

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} | %-5level | %-30logger{0} | %msg%n"
  level:
    root: INFO

    # Core Spring logs
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.boot.autoconfigure: WARN

    # Database / Hibernate logs
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: OFF
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: WARN

    # MailSense custom packages
    org.inn.mailsense: DEBUG

  file:
    name: logs/mailsense.log
    path: logs/